# Generated by Django 5.0.6 on 2024-05-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_customuser',
        ),
    ]
