# Generated by Django 5.0.6 on 2025-07-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
    ]
