# Generated by Django 5.0.6 on 2024-05-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_alter_table_options_alter_table_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
