# Generated by Django 5.0.6 on 2024-05-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0005_restaurant_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='childs_chair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking_system.restaurant'),
            preserve_default=False,
        ),
    ]
